version: "3.3"
services:

    db:
        image: postgres:12.4
        restart: always
        env_file:
            - .env.dev
        ports:
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data

    flask:
        image: flask
        build:
            context: ./
            dockerfile: Dockerfile
        expose:
            - "8000"
        env_file:
          - .env.dev
        volumes:
          - .:/app
        depends_on:
            - db

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./cert:/cert
            - ./conf.d:/etc/nginx/conf.d
        env_file:
            - .env.dev
        depends_on:
            - flask


volumes:
    database-data:
