version: "3.3"
services:


  db:
    image: postgres:10.4
    restart: always
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pss
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data


  flask:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf
    environment:
      NGINX_HOST: foobar.com
      NGINX_PORT: 80
    depends_on:
      - flask


volumes:
  database-data:
